name: iso-test
on: [push]
jobs:
  sparse-test:
    runs-on: Ubuntu-20.04
    steps:
      - run: git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
      - run: git sparse-checkout init --cone
      - run: git sparse-checkout add iso
      - run: git checkout ${GITHUB_SHA}
      - run: git diff origin/main...HEAD --name-only --relative=iso
      - id: "check"
        run: echo "::set-output name=result::$(git diff --exit-code --quiet origin/main --relative=iso > /dev/null || echo $?)"
      - run: echo "${{ steps.check.outputs.result }}"
      - if: steps.check.outputs.result == 1
        run: echo run
