name: iso-test
on: [push]
jobs:
  sparse-test:
    runs-on: Ubuntu-20.04
    steps:
      - run: git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
      - run: git sparse-checkout init --cone
      - run: git sparse-checkout add iso
      - run: git checkout
      - run: git diff origin/main...HEAD --name-only --relative=iso
      - name: run test
        run: |
          if git diff --exit-code --quiet origin/main...HEAD --name-only --relative=iso
          then
            echo "no changes"
          else
            echo "has changes"
            yarn test
          fi
        working-directory: iso
  # check:
  #   runs-on: Ubuntu-20.04
  #   outputs:
  #     active: ${{ steps.checker.active }}
  #   steps:
  #     - uses: actions/checkout@v1
  #     - id: checker
  #       run: |
  #         if git diff origin/develop...HEAD --name-only --relative=packages/a
  #         then
  #           echo "::set-output name=active::true"
  #         fi
  # test:
  #   # needs: check
  #   # if: ${{ needs.check.outputs.active }}
  #   runs-on: Ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: cache node_modules
  #       uses: actions/cache@v1
  #       with:
  #         path: node_modules
  #         key: node_modules_yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           node_modules_yarn-
  #     - name: Use Node.js 15
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 15
  #     - run: yarn install
  #     - run: |
  #         if git diff origin/develop...HEAD --name-only --relative=packages/b
  #         then
  #           yarn test
  #         fi
  #       working-directory: ./pacakages/b
