name: iso-test
on: [push]
env:
  SPARSE_CHECKOUT_DIR: iso
jobs:
  sparsed-check:
    runs-on: Ubuntu-20.04
    outputs:
      changed: ${{ steps.checkout.outputs.changed }}
    steps:
      - id: checkout
        name: sparse checkout
        run: |
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git .
          git sparse-checkout init --cone
          git sparse-checkout add ${SPARSE_CHECKOUT_DIR}
          git checkout ${GITHUB_SHA}
          echo "::set-output name=changed::$(git diff --exit-code --quiet origin/main --relative=${SPARSE_CHECKOUT_DIR} > /dev/null || echo $?)"
  sparsed-test:
    runs-on: Ubuntu-20.04
    needs: [sparsed-check]
    if: needs.sparsed-check.outputs.changed == '1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: yarn test
        working-directory: iso
